### PR TITLE
Adding Join page for group

### PR DESCRIPTION
**Pull request by mmilkin**
Adding Join action for a group.

Now with notifications

### CODE REVIEW

**Comment by mmilkin** [comment]
Added the beginning of the notification (this is now done through meetup, if we want to collect emails we could send emails ourselves.  For now this is synchronous, not sure if we want to complexity of celery or async.

**Comment by nedbat** [comment]
I didn't want to collect emails, it feels like a barrier to people participating, so notifying through Meetup is the right way to do it.

**Comment by mmilkin** [comment]
I agree, we could query meetup for emails using the api but that might be intrusive.

**Comment by nedbat** [comment]
Well, meetup won't give out emails, there's no API to do that.

**Pull request closed without merging**
